<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GEstoque.aspx.cs" Inherits="ProjectSolerun.GEstoque" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Gestão de Estoque</title>

    <style>

    footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

    </style>

</head>
<body>
    <link href="../bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="../bootstrap/js/bootstrap.js"></script>
    <script src="../bootstrap/js/jquery-3.3.1.min.js"></script>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
              
 <a class="navbar-brand" href="PaginaInicial.aspx">Solerun</a>
              
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
                </button>

  <div class="collapse navbar-collapse" id="collapsibleNavbar">       
      <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link">Entrada de Estoque</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="GEstoque_Saida.aspx">Saida de Estoque</a>
      </li>
        </ul>
  </div>  
</nav>

    <form id="form1" runat="server">
   <div class="container">     
        <div>
       <center>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1"  
            allowSorting="True" AllowPaging="True" DataKeyNames="idsolerun_entradaProduto" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" BackColor ="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" GridLines="Horizontal">
             <Columns>
                <asp:BoundField DataField="idsolerun_entradaProduto" HeaderText="ID" SortExpression="idsolerun_entradaProduto" InsertVisible="False" ReadOnly="True" />
                <asp:BoundField DataField="NomeProduto" HeaderText="Nome do Produto" SortExpression="NomeProduto" />
                <asp:BoundField DataField="Codigo" HeaderText="Codigo do Produto" SortExpression="Codigo" />
                <asp:BoundField DataField="Descricao" HeaderText="Descrição" SortExpression="Descricao" />
                <asp:BoundField DataField="Quantidade" HeaderText="Quantidade" SortExpression="Quantidade" />
                <asp:BoundField DataField="ValorCusto" HeaderText="Valor de Custo" SortExpression="ValorCusto" />
                 <asp:BoundField DataField="ValorVenda" HeaderText="Valor de Venda" SortExpression="ValorVenda" />
                 <asp:BoundField DataField="Litragem" HeaderText="Litragem" SortExpression="Litragem" />
            </Columns>
             <FooterStyle BackColor="White" ForeColor="#333333" />
             <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
             <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
             <RowStyle BackColor="White" ForeColor="#333333" />
             <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
             <SortedAscendingCellStyle BackColor="#F7F7F7" />
             <SortedAscendingHeaderStyle BackColor="#487575" />
             <SortedDescendingCellStyle BackColor="#E5E5E5" />
             <SortedDescendingHeaderStyle BackColor="#275353" />
        </asp:GridView>
        </center>
    </div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:dbcerv_solerunConnectionString %>" ProviderName="<%$ ConnectionStrings:dbcerv_solerunConnectionString.ProviderName %>" 
             SelectCommand="SELECT idsolerun_entradaProduto,NomeProduto, Codigo, Descricao, Quantidade, ValorCusto, ValorVenda, Litragem FROM solerun_produto" 
             UpdateCommand="UPDATE solerun_produto SET NomeProduto =@NomeProduto, Codigo =@Codigo, Descricao =@Descricao, Quantidade =@Quantidade, ValorCusto =@ValorCusto, ValorVenda =@ValorVenda, Litragem =@Litragem WHERE idSolerun_entradaProduto = @idSolerun_entradaProduto"
             DeleteCommand="Delete from solerun_Produto where idSolerun_entradaProduto=@idSolerun_entradaProduto">
        </asp:SqlDataSource>
    </div>
       </form>
</body>
</html>
